name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: ture
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - name: Build
        run: hugo --minify

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: p//s Build
        run: |
          GOOS=js GOARCH=wasm go build -o parallel_shooter.wasm .
          mv ./parallel_shooter.wasm ./public/
        working-directory: ./parallel_shooter

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
